# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false # Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state

planner_frequency: 1.0 # The rate in Hz at which to run the global planning loop. If the frequency is set to 0.0, the global planner will only run when a new goal is received or the local planner reports that its path is blocked. New in navigation 1.6.0
planner_patience: 5.0 # How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.
#
controller_frequency: 2.0 # The rate in Hz at which to run the control loop and send velocity commands to the base.
controller_patience: 3.0 # How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.
#
# clearing_rotation_allowed: true # Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space. Note: This parameter is only used when the default recovery behaviors are in use, meaning the user has not set the recovery_behaviors parameter to anything custom.
# recovery_behavior_enabled: true # (bool, default: true) # Whether or not to enable the move_base recovery behaviors to attempt to clear out space.
# max_planning_retries: 10 #  (int32_t, default: -1) # How many times to allow for planning retries before executing recovery behaviors. A value of -1.0 corresponds to an infinite retries.
# # conservative_reset_dist: 3.0 # (double, default: 3.0) # The distance away from the robot in meters beyond which obstacles will be cleared from the costmap when attempting to clear space in the map. Note, this parameter is only used when the default recovery behaviors are used for move_base.
#
oscillation_timeout: 10.0 # How long in seconds to allow for oscillation before executing recovery behaviors. A value of 0.0 corresponds to an infinite timeout. New in navigation 1.3.1
oscillation_distance: 0.5 # How far in meters the robot must move to be considered not to be oscillating. Moving this far resets the timer counting up to the ~oscillation_timeout New in navigation 1.3.1
#
recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
